# Generated by Django 2.0.4 on 2018-04-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('match_date',)},
        ),
    ]
