# Generated by Django 2.0.4 on 2018-04-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='day',
            field=models.CharField(default='Sunday', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='image1',
            field=models.ImageField(default='/images/gr.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='match',
            name='image2',
            field=models.ImageField(default='/images/gr.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='match',
            name='match_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
