# Generated by Django 2.0.4 on 2018-04-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180425_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='id',
        ),
        migrations.AlterField(
            model_name='match',
            name='image1',
            field=models.ImageField(default='/images/srh.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='match',
            name='image2',
            field=models.ImageField(default='/images/srh.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
