# Generated by Django 2.0.4 on 2018-04-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20180426_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand', models.CharField(max_length=30)),
                ('tier1_price', models.IntegerField(default=500)),
                ('tier2_price', models.IntegerField(default=500)),
                ('tier1_availability', models.IntegerField(default=50)),
                ('tier2_availability', models.IntegerField(default=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Match')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='match_book',
            unique_together={('match', 'stand')},
        ),
    ]
