# Generated by Django 2.0.4 on 2018-04-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20180426_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_book',
            name='tier1_availability',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='match_book',
            name='tier1_price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='match_book',
            name='tier2_availability',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='match_book',
            name='tier2_price',
            field=models.IntegerField(default=1000),
        ),
    ]
