# Generated by Django 2.0.4 on 2018-04-26 12:23

import book.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0007_auto_20180426_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand', models.CharField(max_length=30)),
                ('tier_no', models.IntegerField()),
                ('number', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Match')),
                ('user', models.ForeignKey(on_delete=models.SET(book.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tickets',
            unique_together={('match', 'user', 'stand', 'tier_no')},
        ),
    ]
