# Generated by Django 2.0.4 on 2018-04-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20180426_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
    ]
