# Generated by Django 2.0.4 on 2018-04-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(default='Sunrisers Hyderabad', on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='book.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(default='Sunrisers Hyderabad', on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='book.Team'),
        ),
    ]
